### ISSUE TITLE
Improve Movie Class

### ISSUE THREAD

**Issue by rohanbrohan** [svbrodersen/CSC207_project#46]
add new attributes, getters, setters, other methods, to Movie Class to get it to more closely resemble format of JSON objects.

**Comment by feliser** [comment]
After looking it over, I believe it is better to create a new MovieDetailed entity with the extra information needed for the GetMovieInfo use case instead of expanding the current Movie entity, as not all of the attributes in the Movie class are needed for the GetMovieInfo use case (in particular, List<Integer> ratings). Additionally, since the attributes are marked as final they must be initialized and thus I cannot make a constructor excluding the unnecessary data.
